//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>BlogPageTemplate</summary>
	[PublishedContentModel("blogPageTemplate")]
	public partial class BlogPageTemplate : PublishedContentModel, IHeaderProperties
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "blogPageTemplate";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public BlogPageTemplate(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<BlogPageTemplate, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// blogPageBodyText: add blog text
		///</summary>
		[ImplementPropertyType("blogPageBodyText")]
		public string BlogPageBodyText
		{
			get { return this.GetPropertyValue<string>("blogPageBodyText"); }
		}

		///<summary>
		/// blogPageImage: add background image
		///</summary>
		[ImplementPropertyType("blogPageImage")]
		public IPublishedContent BlogPageImage
		{
			get { return this.GetPropertyValue<IPublishedContent>("blogPageImage"); }
		}

		///<summary>
		/// BlogPageTitle: Add blog title here.
		///</summary>
		[ImplementPropertyType("blogPageTitle")]
		public string BlogPageTitle
		{
			get { return this.GetPropertyValue<string>("blogPageTitle"); }
		}

		///<summary>
		/// LogoTitle: Add page title here.
		///</summary>
		[ImplementPropertyType("logoTitle")]
		public string LogoTitle
		{
			get { return Umbraco.Web.PublishedContentModels.HeaderProperties.GetLogoTitle(this); }
		}

		///<summary>
		/// macro In Grid: add macro
		///</summary>
		[ImplementPropertyType("macroInGrid")]
		public Newtonsoft.Json.Linq.JToken MacroInGrid
		{
			get { return Umbraco.Web.PublishedContentModels.HeaderProperties.GetMacroInGrid(this); }
		}

		///<summary>
		/// MacroRender
		///</summary>
		[ImplementPropertyType("macroRender")]
		public IHtmlString MacroRender
		{
			get { return Umbraco.Web.PublishedContentModels.HeaderProperties.GetMacroRender(this); }
		}

		///<summary>
		/// siteLogo
		///</summary>
		[ImplementPropertyType("siteLogo")]
		public IPublishedContent SiteLogo
		{
			get { return Umbraco.Web.PublishedContentModels.HeaderProperties.GetSiteLogo(this); }
		}
	}
}
