//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>BlogItem</summary>
	[PublishedContentModel("blogItem")]
	public partial class BlogItem : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "blogItem";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public BlogItem(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<BlogItem, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// BlogBodyText
		///</summary>
		[ImplementPropertyType("blogBodyText")]
		public IHtmlString BlogBodyText
		{
			get { return this.GetPropertyValue<IHtmlString>("blogBodyText"); }
		}

		///<summary>
		/// BlogDate: add date
		///</summary>
		[ImplementPropertyType("blogDate")]
		public DateTime BlogDate
		{
			get { return this.GetPropertyValue<DateTime>("blogDate"); }
		}

		///<summary>
		/// BlogImage: add blog Image
		///</summary>
		[ImplementPropertyType("blogImage")]
		public IPublishedContent BlogImage
		{
			get { return this.GetPropertyValue<IPublishedContent>("blogImage"); }
		}

		///<summary>
		/// BlogTitle: Add Title for the blog news
		///</summary>
		[ImplementPropertyType("blogTitle")]
		public string BlogTitle
		{
			get { return this.GetPropertyValue<string>("blogTitle"); }
		}

		///<summary>
		/// Post Status: Enter what status your blog post have
		///</summary>
		[ImplementPropertyType("postStatus")]
		public int PostStatus
		{
			get { return this.GetPropertyValue<int>("postStatus"); }
		}
	}
}
