//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>ContactPage</summary>
	[PublishedContentModel("contactPage")]
	public partial class ContactPage : PublishedContentModel, IMessage
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "contactPage";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public ContactPage(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ContactPage, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Email: Ensert your email here
		///</summary>
		[ImplementPropertyType("email")]
		public string Email
		{
			get { return Umbraco.Web.PublishedContentModels.Message.GetEmail(this); }
		}

		///<summary>
		/// Messagecontent: Enter you full message here
		///</summary>
		[ImplementPropertyType("messagecontent")]
		public string Messagecontent
		{
			get { return Umbraco.Web.PublishedContentModels.Message.GetMessagecontent(this); }
		}

		///<summary>
		/// Messagename: Enter message here
		///</summary>
		[ImplementPropertyType("messagename")]
		public string Messagename
		{
			get { return Umbraco.Web.PublishedContentModels.Message.GetMessagename(this); }
		}

		///<summary>
		/// Subject: Enter your subject here
		///</summary>
		[ImplementPropertyType("subject")]
		public string Subject
		{
			get { return Umbraco.Web.PublishedContentModels.Message.GetSubject(this); }
		}

		///<summary>
		/// UmbracoNaviHide: select the item to hide
		///</summary>
		[ImplementPropertyType("umbracoNaviHide")]
		public bool UmbracoNaviHide
		{
			get { return Umbraco.Web.PublishedContentModels.Message.GetUmbracoNaviHide(this); }
		}
	}
}
