//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	// Mixin content Type 1114 with alias "hideControls"
	/// <summary>Hide Controls</summary>
	public partial interface IHideControls : IPublishedContent
	{
		/// <summary>UmbracoNaviHide</summary>
		bool UmbracoNaviHide { get; }
	}

	/// <summary>Hide Controls</summary>
	[PublishedContentModel("hideControls")]
	public partial class HideControls : PublishedContentModel, IHideControls
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "hideControls";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public HideControls(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<HideControls, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// UmbracoNaviHide: Tick this box if you want to hide a menu/page.
		///</summary>
		[ImplementPropertyType("umbracoNaviHide")]
		public bool UmbracoNaviHide
		{
			get { return GetUmbracoNaviHide(this); }
		}

		/// <summary>Static getter for UmbracoNaviHide</summary>
		public static bool GetUmbracoNaviHide(IHideControls that) { return that.GetPropertyValue<bool>("umbracoNaviHide"); }
	}
}
