//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>HomePage</summary>
	[PublishedContentModel("homePage")]
	public partial class HomePage : PublishedContentModel, IHeaderProperties, IHideControls, ISEO
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "homePage";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public HomePage(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<HomePage, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// LogoTitle: Add page title here.
		///</summary>
		[ImplementPropertyType("logoTitle")]
		public string LogoTitle
		{
			get { return Umbraco.Web.PublishedContentModels.HeaderProperties.GetLogoTitle(this); }
		}

		///<summary>
		/// macro In Grid: add macro
		///</summary>
		[ImplementPropertyType("macroInGrid")]
		public Newtonsoft.Json.Linq.JToken MacroInGrid
		{
			get { return Umbraco.Web.PublishedContentModels.HeaderProperties.GetMacroInGrid(this); }
		}

		///<summary>
		/// MacroRender
		///</summary>
		[ImplementPropertyType("macroRender")]
		public IHtmlString MacroRender
		{
			get { return Umbraco.Web.PublishedContentModels.HeaderProperties.GetMacroRender(this); }
		}

		///<summary>
		/// siteLogo
		///</summary>
		[ImplementPropertyType("siteLogo")]
		public IPublishedContent SiteLogo
		{
			get { return Umbraco.Web.PublishedContentModels.HeaderProperties.GetSiteLogo(this); }
		}

		///<summary>
		/// UmbracoNaviHide: Tick this box if you want to hide a menu/page.
		///</summary>
		[ImplementPropertyType("umbracoNaviHide")]
		public bool UmbracoNaviHide
		{
			get { return Umbraco.Web.PublishedContentModels.HideControls.GetUmbracoNaviHide(this); }
		}

		///<summary>
		/// SiteDescription: Enter site description here
		///</summary>
		[ImplementPropertyType("siteDescription")]
		public string SiteDescription
		{
			get { return Umbraco.Web.PublishedContentModels.SEO.GetSiteDescription(this); }
		}

		///<summary>
		/// SiteKeyWords: Enter sites key words for SEO
		///</summary>
		[ImplementPropertyType("siteKeyWords")]
		public string SiteKeyWords
		{
			get { return Umbraco.Web.PublishedContentModels.SEO.GetSiteKeyWords(this); }
		}

		///<summary>
		/// siteTitle: Enter site title here.
		///</summary>
		[ImplementPropertyType("siteTitle")]
		public string SiteTitle
		{
			get { return Umbraco.Web.PublishedContentModels.SEO.GetSiteTitle(this); }
		}
	}
}
