//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	// Mixin content Type 2224 with alias "message"
	/// <summary>Message</summary>
	public partial interface IMessage : IPublishedContent
	{
		/// <summary>Email</summary>
		string Email { get; }

		/// <summary>Messagecontent</summary>
		string Messagecontent { get; }

		/// <summary>Messagename</summary>
		string Messagename { get; }

		/// <summary>Subject</summary>
		string Subject { get; }

		/// <summary>UmbracoNaviHide</summary>
		bool UmbracoNaviHide { get; }
	}

	/// <summary>Message</summary>
	[PublishedContentModel("message")]
	public partial class Message : PublishedContentModel, IMessage
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "message";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Message(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Message, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Email: Ensert your email here
		///</summary>
		[ImplementPropertyType("email")]
		public string Email
		{
			get { return GetEmail(this); }
		}

		/// <summary>Static getter for Email</summary>
		public static string GetEmail(IMessage that) { return that.GetPropertyValue<string>("email"); }

		///<summary>
		/// Messagecontent: Enter you full message here
		///</summary>
		[ImplementPropertyType("messagecontent")]
		public string Messagecontent
		{
			get { return GetMessagecontent(this); }
		}

		/// <summary>Static getter for Messagecontent</summary>
		public static string GetMessagecontent(IMessage that) { return that.GetPropertyValue<string>("messagecontent"); }

		///<summary>
		/// Messagename: Enter message here
		///</summary>
		[ImplementPropertyType("messagename")]
		public string Messagename
		{
			get { return GetMessagename(this); }
		}

		/// <summary>Static getter for Messagename</summary>
		public static string GetMessagename(IMessage that) { return that.GetPropertyValue<string>("messagename"); }

		///<summary>
		/// Subject: Enter your subject here
		///</summary>
		[ImplementPropertyType("subject")]
		public string Subject
		{
			get { return GetSubject(this); }
		}

		/// <summary>Static getter for Subject</summary>
		public static string GetSubject(IMessage that) { return that.GetPropertyValue<string>("subject"); }

		///<summary>
		/// UmbracoNaviHide: select the item to hide
		///</summary>
		[ImplementPropertyType("umbracoNaviHide")]
		public bool UmbracoNaviHide
		{
			get { return GetUmbracoNaviHide(this); }
		}

		/// <summary>Static getter for UmbracoNaviHide</summary>
		public static bool GetUmbracoNaviHide(IMessage that) { return that.GetPropertyValue<bool>("umbracoNaviHide"); }
	}
}
