//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>ProjectsTemplate</summary>
	[PublishedContentModel("projectsTemplate")]
	public partial class ProjectsTemplate : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "projectsTemplate";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public ProjectsTemplate(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ProjectsTemplate, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// ProjectPageImage: Insert image for the project page
		///</summary>
		[ImplementPropertyType("projectPageImage")]
		public IPublishedContent ProjectPageImage
		{
			get { return this.GetPropertyValue<IPublishedContent>("projectPageImage"); }
		}

		///<summary>
		/// ProjectPageSubTitle: add the main project sub title.
		///</summary>
		[ImplementPropertyType("projectPageSubTitle")]
		public string ProjectPageSubTitle
		{
			get { return this.GetPropertyValue<string>("projectPageSubTitle"); }
		}

		///<summary>
		/// ProjectPageTitle: Add the main title for the project.
		///</summary>
		[ImplementPropertyType("projectPageTitle")]
		public string ProjectPageTitle
		{
			get { return this.GetPropertyValue<string>("projectPageTitle"); }
		}
	}
}
