//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	// Mixin content Type 1081 with alias "sEO"
	/// <summary>SEO</summary>
	public partial interface ISEO : IPublishedContent
	{
		/// <summary>SiteDescription</summary>
		string SiteDescription { get; }

		/// <summary>SiteKeyWords</summary>
		string SiteKeyWords { get; }

		/// <summary>siteTitle</summary>
		string SiteTitle { get; }
	}

	/// <summary>SEO</summary>
	[PublishedContentModel("sEO")]
	public partial class SEO : PublishedContentModel, ISEO
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "sEO";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public SEO(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<SEO, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// SiteDescription: Enter site description here
		///</summary>
		[ImplementPropertyType("siteDescription")]
		public string SiteDescription
		{
			get { return GetSiteDescription(this); }
		}

		/// <summary>Static getter for SiteDescription</summary>
		public static string GetSiteDescription(ISEO that) { return that.GetPropertyValue<string>("siteDescription"); }

		///<summary>
		/// SiteKeyWords: Enter sites key words for SEO
		///</summary>
		[ImplementPropertyType("siteKeyWords")]
		public string SiteKeyWords
		{
			get { return GetSiteKeyWords(this); }
		}

		/// <summary>Static getter for SiteKeyWords</summary>
		public static string GetSiteKeyWords(ISEO that) { return that.GetPropertyValue<string>("siteKeyWords"); }

		///<summary>
		/// siteTitle: Enter site title here.
		///</summary>
		[ImplementPropertyType("siteTitle")]
		public string SiteTitle
		{
			get { return GetSiteTitle(this); }
		}

		/// <summary>Static getter for siteTitle</summary>
		public static string GetSiteTitle(ISEO that) { return that.GetPropertyValue<string>("siteTitle"); }
	}
}
